# Generated by Django 2.2.7 on 2019-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_board_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('sandwitch', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('bread', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
            ],
        ),
    ]
