# Generated by Django 2.2.7 on 2019-11-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_board_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
    ]
