# Generated by Django 2.2.7 on 2019-11-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, upload_to='boards/%Y/%m/%d'),
        ),
    ]
